[package]
name = "zk-material"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true, features = ["derive", "env"] }
num-bigint = { workspace = true }
num-primes = { workspace = true }
num-traits = { workspace = true }
rand = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
