// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterRequest {
    #[prost(string, tag = "1")]
    pub user: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub y1: i64,
    #[prost(int64, tag = "3")]
    pub y2: i64,
}
impl ::prost::Name for RegisterRequest {
    const NAME: &'static str = "RegisterRequest";
    const PACKAGE: &'static str = "zkp_auth";
    fn full_name() -> ::prost::alloc::string::String {
        "zkp_auth.RegisterRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/zkp_auth.RegisterRequest".into()
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterResponse {}
impl ::prost::Name for RegisterResponse {
    const NAME: &'static str = "RegisterResponse";
    const PACKAGE: &'static str = "zkp_auth";
    fn full_name() -> ::prost::alloc::string::String {
        "zkp_auth.RegisterResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/zkp_auth.RegisterResponse".into()
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthenticationChallengeRequest {
    #[prost(string, tag = "1")]
    pub user: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub r1: i64,
    #[prost(int64, tag = "3")]
    pub r2: i64,
}
impl ::prost::Name for AuthenticationChallengeRequest {
    const NAME: &'static str = "AuthenticationChallengeRequest";
    const PACKAGE: &'static str = "zkp_auth";
    fn full_name() -> ::prost::alloc::string::String {
        "zkp_auth.AuthenticationChallengeRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/zkp_auth.AuthenticationChallengeRequest".into()
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthenticationChallengeResponse {
    #[prost(string, tag = "1")]
    pub auth_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub c: i32,
}
impl ::prost::Name for AuthenticationChallengeResponse {
    const NAME: &'static str = "AuthenticationChallengeResponse";
    const PACKAGE: &'static str = "zkp_auth";
    fn full_name() -> ::prost::alloc::string::String {
        "zkp_auth.AuthenticationChallengeResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/zkp_auth.AuthenticationChallengeResponse".into()
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthenticationAnswerRequest {
    #[prost(string, tag = "1")]
    pub auth_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub s: i32,
}
impl ::prost::Name for AuthenticationAnswerRequest {
    const NAME: &'static str = "AuthenticationAnswerRequest";
    const PACKAGE: &'static str = "zkp_auth";
    fn full_name() -> ::prost::alloc::string::String {
        "zkp_auth.AuthenticationAnswerRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/zkp_auth.AuthenticationAnswerRequest".into()
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthenticationAnswerResponse {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
}
impl ::prost::Name for AuthenticationAnswerResponse {
    const NAME: &'static str = "AuthenticationAnswerResponse";
    const PACKAGE: &'static str = "zkp_auth";
    fn full_name() -> ::prost::alloc::string::String {
        "zkp_auth.AuthenticationAnswerResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/zkp_auth.AuthenticationAnswerResponse".into()
    }
}
/// Generated server implementations.
pub mod auth_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with AuthServer.
    #[async_trait]
    pub trait Auth: Send + Sync + 'static {
        async fn register(
            &self,
            request: tonic::Request<super::RegisterRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RegisterResponse>,
            tonic::Status,
        >;
        async fn create_authentication_challenge(
            &self,
            request: tonic::Request<super::AuthenticationChallengeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AuthenticationChallengeResponse>,
            tonic::Status,
        >;
        async fn verify_authentication(
            &self,
            request: tonic::Request<super::AuthenticationAnswerRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AuthenticationAnswerResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct AuthServer<T: Auth> {
        inner: _Inner<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    struct _Inner<T>(Arc<T>);
    impl<T: Auth> AuthServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for AuthServer<T>
    where
        T: Auth,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/zkp_auth.Auth/Register" => {
                    #[allow(non_camel_case_types)]
                    struct RegisterSvc<T: Auth>(pub Arc<T>);
                    impl<T: Auth> tonic::server::UnaryService<super::RegisterRequest>
                    for RegisterSvc<T> {
                        type Response = super::RegisterResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RegisterRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Auth>::register(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = RegisterSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/zkp_auth.Auth/CreateAuthenticationChallenge" => {
                    #[allow(non_camel_case_types)]
                    struct CreateAuthenticationChallengeSvc<T: Auth>(pub Arc<T>);
                    impl<
                        T: Auth,
                    > tonic::server::UnaryService<super::AuthenticationChallengeRequest>
                    for CreateAuthenticationChallengeSvc<T> {
                        type Response = super::AuthenticationChallengeResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::AuthenticationChallengeRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Auth>::create_authentication_challenge(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = CreateAuthenticationChallengeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/zkp_auth.Auth/VerifyAuthentication" => {
                    #[allow(non_camel_case_types)]
                    struct VerifyAuthenticationSvc<T: Auth>(pub Arc<T>);
                    impl<
                        T: Auth,
                    > tonic::server::UnaryService<super::AuthenticationAnswerRequest>
                    for VerifyAuthenticationSvc<T> {
                        type Response = super::AuthenticationAnswerResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AuthenticationAnswerRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Auth>::verify_authentication(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = VerifyAuthenticationSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", "12")
                                .header("content-type", "application/grpc")
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: Auth> Clone for AuthServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: Auth> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(Arc::clone(&self.0))
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: Auth> tonic::server::NamedService for AuthServer<T> {
        const NAME: &'static str = "zkp_auth.Auth";
    }
}
