// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MaterialRequest {
    /// user is the user id
    #[prost(string, tag = "1")]
    pub user: ::prost::alloc::string::String,
    /// q is the prime order of the group.
    ///
    /// The prime order is optional because of the following reasons:
    ///
    /// 1. If it is present it tries to generate using that prime order if it is valid
    /// 2. If it is not present it tries to generate using a random prime order
    #[prost(int64, optional, tag = "2")]
    pub q: ::core::option::Option<i64>,
}
impl ::prost::Name for MaterialRequest {
    const NAME: &'static str = "MaterialRequest";
    const PACKAGE: &'static str = "zkp_material";
    fn full_name() -> ::prost::alloc::string::String {
        "zkp_material.MaterialRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/zkp_material.MaterialRequest".into()
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MaterialResponse {
    #[prost(int64, tag = "2")]
    pub g: i64,
    #[prost(int64, tag = "3")]
    pub h: i64,
}
impl ::prost::Name for MaterialResponse {
    const NAME: &'static str = "MaterialResponse";
    const PACKAGE: &'static str = "zkp_material";
    fn full_name() -> ::prost::alloc::string::String {
        "zkp_material.MaterialResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/zkp_material.MaterialResponse".into()
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryRequest {
    #[prost(string, tag = "1")]
    pub user: ::prost::alloc::string::String,
}
impl ::prost::Name for QueryRequest {
    const NAME: &'static str = "QueryRequest";
    const PACKAGE: &'static str = "zkp_material";
    fn full_name() -> ::prost::alloc::string::String {
        "zkp_material.QueryRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/zkp_material.QueryRequest".into()
    }
}
/// Generated server implementations.
pub mod material_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with MaterialServer.
    #[async_trait]
    pub trait Material: Send + Sync + 'static {
        /// Generate generates a new material for the user id
        /// The material is a pair of integers (g, h) such that g and h are generator of the same group with
        /// prime order q. The group is defined by the user id.
        ///
        /// If the user id already exists it returns the same material.
        ///
        /// Possible Errors:
        ///
        /// - InvalidArgument: If q is not a prime number
        /// - AlreadyExists: If the user id already exists
        async fn generate(
            &self,
            request: tonic::Request<super::MaterialRequest>,
        ) -> std::result::Result<
            tonic::Response<super::MaterialResponse>,
            tonic::Status,
        >;
        /// Get returns the material for the user id
        ///
        /// Possible Errors:
        /// - NotFound: If the user id does not exist
        async fn get(
            &self,
            request: tonic::Request<super::QueryRequest>,
        ) -> std::result::Result<
            tonic::Response<super::MaterialResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct MaterialServer<T: Material> {
        inner: _Inner<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    struct _Inner<T>(Arc<T>);
    impl<T: Material> MaterialServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for MaterialServer<T>
    where
        T: Material,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/zkp_material.Material/Generate" => {
                    #[allow(non_camel_case_types)]
                    struct GenerateSvc<T: Material>(pub Arc<T>);
                    impl<T: Material> tonic::server::UnaryService<super::MaterialRequest>
                    for GenerateSvc<T> {
                        type Response = super::MaterialResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MaterialRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Material>::generate(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GenerateSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/zkp_material.Material/Get" => {
                    #[allow(non_camel_case_types)]
                    struct GetSvc<T: Material>(pub Arc<T>);
                    impl<T: Material> tonic::server::UnaryService<super::QueryRequest>
                    for GetSvc<T> {
                        type Response = super::MaterialResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::QueryRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Material>::get(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", "12")
                                .header("content-type", "application/grpc")
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: Material> Clone for MaterialServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: Material> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(Arc::clone(&self.0))
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: Material> tonic::server::NamedService for MaterialServer<T> {
        const NAME: &'static str = "zkp_material.Material";
    }
}
