name: Build Rust

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always


jobs:
  build-rust:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "26.x"

      - name: Formatting
        run: cargo fmt --all -- --check

      - name: Linting
        run: cargo clippy --all-targets --all-features --workspace -- -D warnings

      - name: Build and Tests
        run: cargo test
